### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by AirOne01** [AirOne01/x#8]
- [ ] Implement GitHub cli tool
- [ ] Implement .dotfiles
  - [ ] Clone .dotfiles repo from account
  - [ ] Choose .dotfiles to fetch
  - [ ] Add new dotfiles from local
  - [ ] Update .dotfiles repo
  - [ ] App "shopping" list
